# For more info on HTTP files go to https://aka.ms/vs/httpfile

@Worldpay.US.Proxy_HostAddress = https://localhost:7296
@ApiVersion = v2

# ===================
# Swagger
# ===================
GET {{Worldpay.US.Proxy_HostAddress}}/raft/swagger/v2/swagger.json
Accept: application/json

###

GET {{Worldpay.US.Proxy_HostAddress}}/raft/swagger/v3/swagger.json
Accept: application/json

###

GET {{Worldpay.US.Proxy_HostAddress}}/express/swagger/v2/swagger.json
Accept: application/json

###

GET {{Worldpay.US.Proxy_HostAddress}}/express/swagger/v4/swagger.json
Accept: application/json

###

# ===================
# Payments Controller
# ===================
GET {{Worldpay.US.Proxy_HostAddress}}/raft/api/{{ApiVersion}}/payments/authorize
Accept: application/json

###

GET {{Worldpay.US.Proxy_HostAddress}}/express/api/{{ApiVersion}}/payments/authorize
Accept: application/json

###

# will round robin
GET {{Worldpay.US.Proxy_HostAddress}}/api/{{ApiVersion}}/payments/authorize
Accept: application/json

###

# ===================
# Debug Controller
# ===================

GET {{Worldpay.US.Proxy_HostAddress}}/raft/api/{{ApiVersion}}/debug/headers
Accept: application/json

###

GET {{Worldpay.US.Proxy_HostAddress}}/express/api/{{ApiVersion}}/debug/headers
Accept: application/json

###

# does not make sense to use that you would use the load balanced config, but it works
GET {{Worldpay.US.Proxy_HostAddress}}/api/{{ApiVersion}}/debug/headers
Accept: application/json

###

# ===================
# Health Checks (should be blocked from the outside)
# ===================
GET {{Worldpay.US.Proxy_HostAddress}}/express/health
Accept: application/json

###

GET {{Worldpay.US.Proxy_HostAddress}}/raft/health
Accept: application/json

###